config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users
 resources :recipes do
  resource :favorites, only: [:create, :destroy]
  resources :recipe_comments, only: [:create, :destroy]
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id,{presence: true}
  validates :recipe_id,{presence: true}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :recipe_comments, dependent: :destroy
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipe, dependent: :destroy
  has_many :recipe_comments, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  	 @user = current_user
  end


 private
  def user_params
  	  params.require(:user).permit(:name, :introduction , :profile_image)
  end
end

app/controllers/likes_controller.rb
class LikeController < ApplicationController


 end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController
 def create
 	recipe = Recipe.find(params[:recipe_id])
    comment = current_user.recipe_comments.new(recipe_comment_params)
    comment.recipe_id = recipe.id
    comment.save
    redirect_to recipe_path(recipe)
 end

 def destroy
 	RecipeComment.find_by(id: params[:id], recipe_id: params[:recipe_id]).destroy
    redirect_to recipe_path(params[:recipe_id])
 end

 private
  def recipe_comment_params
    params.require(:recipe_comment).permit(:comment)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_comment = RecipeComment.new
  end

  def new
    @recipe = Recipe.new
  end

  def index
     @recipe = Recipe.new
     @recipes = Recipe.all

  end

  def edit
     @recipe = Recipe.find(params[:id])
     unless @recipe.user_id == current_user.id
      redirect_to recipi_path
     end
  end

  def create
      @recipe = Recipe.new(recipe_params)
      @recipe.user = current_user
      if @recipe.save
       redirect_to recipes_path
      end
  end

  def destroy
     @recipe = Recipe.find(params[:id])
     @recipe.destroy
     redirect_to recipe_path
  end

  def update
     @recipe = Recipe.find(params[:id])
     @recipe.update(recipe_params)
     redirect_to recipe_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :image, :material, :procedure)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  end

  def edit
  	 @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  end

  private
  def user_params
  	  params.require(:user).permit(:name, :introduction , :profile_image)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class ="container">
 <div class="row">
  <div class="col-xs-3">
   <% if user_signed_in? %>
    <h2>会員情報</h2>
     <table class="table">
      <%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg",  size: "100x100"%>

      <tr>
        <th>名前</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>自己紹介</th>
        <th><%= @user.introduction %></th>
      </tr>
    </table>
     <div class="row">
      <tr>
       <th> <%= link_to "会員情報編集" , edit_user_path(@user), class: 'btn btn-primary' %> </th>
      </tr>
     </div>
     <div class="row">
      <tr>
     <th> <%= link_to "レシピを書く" ,  new_recipe_path, class: 'btn btn-success' %> </th>
      </tr>
     </div>
    </table>
<% end %>
  </div>
  <div class="col-xs-9">
   <div class="main-image">
    <div class="main-text">
     <p>
      自宅で料理を楽しもう！<br>
      このサイトは料理を手軽に検索できるサイトです。 <br>
      会員でない方も閲覧はできますが、
      登録するとレシピ投稿やコメント機能が使え <br>
      より便利に本サイトを利用することができます。<br>
     </p>
    </div>
   </div>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cooklife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-dark" style="background-color: #c22a1f">
   <div class="container">
    <nav class= "nav navbar-nav navbar-left">
      <a class="navbar-brand" href="/">Cooklife</a>
    </nav>
     <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to " ホーム", root_path, class: "glyphicon glyphicon-home home" %></li>
       <li><%= link_to " レシピ" , recipes_path,  class: "glyphicon glyphicon-user users" %></li>
       <li><%= link_to " logout" ,destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out sign_out" %></li>
       <% else %>
       <li><%= link_to " ホーム", root_path, class: "glyphicon glyphicon-home home" %></li>
       <li><%= link_to " レシピ" , recipes_path,  class: "glyphicon glyphicon-user users" %></li>
      <li><%= link_to "新規登録" , new_user_registration_path , class: "glyphicon glyphicon-edit sign_up" %></li>
       <li><%= link_to "ログイン" ,new_user_session_path , class: "glyphicon glyphicon-log-in sign_in" %></li>
      <% end %>
     </ul>
    </nav>
</header>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |f| %>
<h1>レシピ編集</h1>
  <h4>レシピタイトル</h4>
  <%= f.text_field :title %>
  <h4>材料・分量</h4>
  <%= f.text_field :material %>
  <h4>紹介文</h4>
  <%= f.text_area :body %>
  <h4>作り方</h4>
  <%= f.text_area :procedure %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>  <%= f.submit '保存' %>

<% end %>

app/views/recipes/index.html.erb
<div class ="container">
 <div class = "col-xs-9">
  <h2>レシピ一覧</h2>
  <table class="table">
   <thead>
   	<tr>
   	 <th></th>
   	 <th>タイトル</th>
   	 <th>紹介</th>
   	 <th>作成者・コメント数</th>
   	 <th colspan="4"></th>
   	</tr>
   <% @recipes.each do |recipe| %>
    <tr>
     <th><%= attachment_image_tag recipe.user, :profile_image , format: "jpeg" , fallback:'no_image.jpg' ,size:'50x50' %>
     </th>
     <th><%= link_to recipe.title, "recipes/#{recipe.id}" %></th>
     <th><%= recipe.body %></th>
     <th>
      <ul class="inline-meta">
       <li>By
        <%= recipe.user.name %>
       </li>
       <li>
       <%= link_to "#{recipe.recipe_comments.count} コメント", recipe_path(recipe.id) %>
       </li>
      </ul>
    </th>
    </tr>
   <% end %>
   </thead>
  </table>
 </div>
</div>

app/views/recipes/new.html.erb
<h1>レシピ投稿</h1>
<%= form_for(@recipe) do |f| %>
  <h4>レシピタイトル</h4>
  <%= f.text_field :title %>
  <h4>材料・分量</h4>
  <%= f.text_field :material %>
  <h4>紹介文</h4>
  <%= f.text_area :body %>
  <h4>作り方</h4>
  <%= f.text_area :procedure %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>  <%= f.submit '投稿' %>

<% end %>

app/views/recipes/show.html.erb
<h2>タイトル</h2>
<p><%= @recipe.title %></p>
<h2>材料・分量</h2>
<p><%= @recipe.material %></p>
<h2>説明</h2>
<p><%= @recipe.body %></p>
<h2>作り方</h2>
<p><%= @recipe.procedure %></p>
<th>
<%= attachment_image_tag @recipe, :image, :fill, 50, 50, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
</th>
<li>
  <i class="fa fa-comment"></i>
  <a href="#comments"><%= @recipe.recipe_comments.count %></a>
</li>
<div class="comment-list bt style-2" id="comments">
  <div class="float-wrapper">
    <h2 class="comment-count"><%= @recipe.recipe_comments.count %>件コメント</h2>
  </div>
 <ol>
  <% @recipe.recipe_comments.each do |recipe_comment| %>
    <li class="comment">
      <div class="comment-body bb">
        <div class="comment-avatar">
          <div class="avatar">
            <%= image_tag('no_image.jpg', style: "width: 60px; height: 60px;") %>
          </div>
        </div>
        <div class="comment-text">
          <div class="comment-author clearfix">
            <a href="#" class="link-author"><%= recipe_comment.user.name %></a>
            <span class="comment-meta">
              <span class="comment-date"><%= recipe_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
          </div>
          <div class="comment-entry"><%= recipe_comment.comment %></div>
           <% if recipe_comment.user == current_user %>
            <div>
              <%= link_to "削除", recipe_recipe_comment_path(recipe_comment.recipe, recipe_comment), method: :delete, class: "btn btn-danger pull-right" %>
            </div>
           <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ol>
</div>
<%= form_for [@recipe, @recipe_comment] do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<% if @recipe.user == current_user %>
 <td>
  <%= link_to 'Edit', edit_recipe_path , class: "btn-sm btn-success"%>
 </td>
 <td>
 <%= link_to 'Destroy', recipe_path(@recipe), method: :delete, data: { confirm: '本当に消しますか？'}, class: "btn-sm btn-danger" %>
 </td>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
 <div class ="container">
  <h2>会員情報</h2>
  <div class="field">
   <label for="user_name">名前</label>
   <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>
  <div class="field">
  <label for="user_image">プロフィール画像</label>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>
  <div class="field">
   <label for="user_introduction">自己紹介</label>
    <%= f.text_field :introduction, autofocus: true, autocomplete: "introduction" %>
  </div>
  <div class="actions">
   <%= f.submit '更新' %>
   </div>
 </div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>